apiVersion: v1
kind: Service
metadata:
  name: hellogcp-ping-service-go
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hellogcp-ping
    language: go
